# 基本設定
CAM_INDEX = 0
IMG_SIZE = 640
BASE_MODEL_PATH = "models/yolov8n.pt"
POSE_MODEL_PATH = "models/yolov8n-pose.pt"
WEAPON_MODEL_PATH = "models/weapon_final.pt"
ALERT_WAV_PATH = "assets/alert.wav"

CLOSE_LABEL = "person"

DANGER_THRESHOLD = 0.22
WARN_RATIO = 0.70

DANGER_FRAMES = 3
SAFE_FRAMES = 6
TELEGRAM_COOLDOWN = 10.0

RISK_WARNING_SCORE = 40
RISK_DANGER_SCORE = 80

DEFAULT_TOGGLES = {
    "person_close": True,
    "weapon_detection": True,
    "aggro_detection": True,
    "noise_detection": True,
    "risk_fusion": True,
    "alert_system": True,
}

# 武器偵測參數
WEAPON_CONF = 0.18
WEAPON_IOU = 0.45
WEAPON_WINDOW = 8
WEAPON_HIT_FRAMES = 3

ROI_EXPAND = 0.15
MIN_WEAPON_BOX_AREA =180

WEAPON_ALLOWED_NAMES = {"gun", "knife"}
WEAPON_MIN_CONF_HIT = 0.40
WEAPON_TOP1_ONLY = True
WEAPON_MIN_BOX_AR = 1.6
WEAPON_MAX_BOX_AR = 11.0

WEAPON_ROI_LOWER_ONLY = True
WEAPON_ROI_LOWER_START = 0.40

# Pose Aggro 參數
AGGRO_WINDOW = 8
AGGRO_HIT_FRAMES = 4
AGGRO_MIN_PERSON_AREA = 3500

POSE_CONF = 0.25
POSE_IOU = 0.45
POSE_MIN_KPT_CONF = 0.35
POSE_RUN_EVERY_N_FRAMES = 2

POSE_WRIST_SPEED_THR = 2.2
POSE_ANKLE_SPEED_THR = 2.0
POSE_JERK_THR = 1.2
POSE_ARM_EXT_THR = 1.35
POSE_LEG_EXT_THR = 1.30
CAM_SHAKE_THR = 18.0

# Noise 參數
NOISE_SAMPLE_RATE = 16000
NOISE_BLOCK_SEC = 0.5
NOISE_FLOOR_ALPHA = 0.01
NOISE_WARN_DELTA_DB = 25.0
NOISE_DANGER_DELTA_DB = 32.0
NOISE_MIN_DBFS = -80.0
NOISE_CONFIRM_WINDOW = 6
NOISE_DANGER_HIT_FRAMES = 2
NOISE_WARN_HIT_FRAMES = 2
